### PR TITLE
Hide menu bar by default on Windows and Linux. Alt toggles it.

### PR DESCRIPTION
**Pull request by idle-zealot**

### CODE REVIEW

**Comment by PalmerAL** [comment]
Looks great! I didn't know electron had a preference for this.

I'm wondering, though, how many people know that alt shows the menu bar? Chrome and Firefox have a side menu, so you don't need the menu bar to access features, but in Min a lot of features are only available in the menu bar. Is this somethig a lot of apps do on those platforms?

**Comment by idle-zealot** [comment]
Alt or Ctrl+M to toggle menu bar is the standard, though most applications have the menu bar shown by default. That said, other electron applications usually have autohide off by default, and allow one to toggle it in the View menu.

**Comment by PalmerAL** [comment]
OK, I'll merge this and file an issue about adding an option: #74.

**Comment by TheInitializer** [comment]
Doesn't seem to be working on Windows 10 x64

**Pull request merged**
