### PR TITLE
Adds debian build categories and mime types

### PR DESCRIPTION
**Pull request by emersion**
These are the same as Firefox.

### CODE REVIEW

**Comment by emersion** [comment]
Fixes #92 on Linux

**Comment by PalmerAL** [comment]
I think Electron needs to add an event for when a link is opened on Linux for this to work, right?

**Comment by PalmerAL** [comment]
Nevermind, the comment in #84 answers this.

**Comment by emersion** [comment]
`grunt-electron-installer-debian` adds `%U` after the command name, so it will spawn something like `min http://example.org`.

**Comment by PalmerAL** [comment]
OK, I guess I'll go ahead and merge this. I was hoping to test it out, but Ubuntu isn't working in virtualbox, even after I go back to a snapshot that worked before.

**Pull request merged**
